import jsPDF from 'jspdf';
import { contentBlocks } from '../data/content';

export function generateSMSPDF(completedData, riskProfile, contentMap) {
    const doc = new jsPDF();
    const lineHeight = 10;
    let cursorY = 20;

    // Title Page
    doc.setFontSize(24);
    doc.text("Safety Management System", 105, 100, { align: "center" });
    doc.setFontSize(16);
    doc.text("Generated by VoltSafe Systems", 105, 120, { align: "center" });

    doc.setFontSize(12);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 105, 140, { align: "center" });
    doc.text(`Risk Level: ${riskProfile.level}`, 105, 150, { align: "center" });

    doc.addPage();

    // Content Blocks
    doc.setFontSize(16);
    doc.text("System Content", 20, 20);
    cursorY = 40;

    doc.setFontSize(12);

    Object.entries(contentMap).forEach(([key, isActive]) => {
        if (isActive && contentBlocks[key]) {
            const block = contentBlocks[key];

            // Check page break
            if (cursorY > 250) {
                doc.addPage();
                cursorY = 20;
            }

            // Title
            doc.setFont(undefined, 'bold');
            doc.text(block.title, 20, cursorY);
            cursorY += 10;

            // Body
            doc.setFont(undefined, 'normal');
            const splitText = doc.splitTextToSize(block.body.trim(), 170);
            doc.text(splitText, 20, cursorY);

            cursorY += (splitText.length * 7) + 15;
        }
    });

    // Risk Profile Page
    doc.addPage();
    doc.setFontSize(16);
    doc.text("Risk Profile & Audit Flags", 20, 20);
    cursorY = 40;

    riskProfile.flags.forEach(flag => {
        doc.setFont(undefined, 'bold');
        doc.setTextColor(255, 0, 0); // Red
        doc.text(`[${flag.severity}] ${flag.label}`, 20, cursorY);
        cursorY += 7;

        doc.setFont(undefined, 'normal');
        doc.setTextColor(0, 0, 0); // Black
        doc.text(flag.message, 20, cursorY);
        cursorY += 15;
    });

    doc.save("VoltSafe_SMS_Pack.pdf");
}
